# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: release
  - r: devel
  - r: oldrel
  - r: 3.5


addons:
  apt:
    update: true
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libfftw3-dev
      - cargo
      - gsfonts
