# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

#minimal requirements for travis and R
language: R
cache: packages

sudo: false

#Define multiple R-versions; this is for old release and current
r:
  - oldrel
  - release

# Set one of your dependencies from CRAN
#By default, Travis CI will find all R packages listed as dependencies in your package’s DESCRIPTION file, and install them from CRAN.
packages:
  - covr
  
# Set one of your dependencies from bioconductor
bioc_packages:
  - ggtree
  - treeio

# Install all system dependencies of ImageMagick. Documented here: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5
addons:
  apt:
    update: true
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libfftw3-dev
      - cargo
      - gsfonts
      
#test multiple operating systems
os:
  - linux
  - osx
#  - windows #windows build are in early access stage and r is not supported
#on the windows build environment

script:
- R CMD build .
- R CMD check *tar.gz

after_success:
- Rscript -e 'library(covr); codecov()'

#neev to confirm if I need the below lines
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"




