# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
bioc_packages:
  - ggtree
  - treeio
  
os:
  - linux
  - osx

apt_packages:
  - libfftw3-dev

r_packages:
  - covr
  - ape
  - ggplot2
  - tidyr
  - phytools

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
- Rscript -e 'library(covr); codecov()'

addons:
  apt:
    update: true
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libfftw3-dev
      - cargo
      - gsfonts